baseurl = "http://www.resourcefulcomputing.com/"
languageCode = "en-us"
title = "Resourceful Computing"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
# Define the number of posts per site
paginate = 10
footnotereturnlinkcontents = "↩"
theme = "hugo-icarus-theme"


[permalinks]
    post = "/post/:slug/"
#    post = "/:year/:month/:day/:slug"


[params]
    # Tell me who you are

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

# Customizations
[params.publisher]
    name = "Resourceful Computing"

[params.publisherimage]
    url    = "http://www.resourcefulcomputing.com/images/kotlin/kotlin-logo-200x200.png"
    height = "256"
    width  = "256"

[params.author]
    url = "http://www.randolphkahle.info"
    name = "Randolph Kahle"
    nickName = "Randy Kahle"
    honorificSuffix = "MBA"
    author = "Randolph Kahle"
    bio = "Architect - Mentor - Trainer - Consultant"
    location = "Fort Collins, CO"
    site_description = "Guide to Resourceful Computing"
    copyright  = "Copyright Databliss, LLC 2016 Powered by [Hugo](//gohugo.io). Theme by [PPOffice](http://github.com/ppoffice)."
    avatar = "images/randolphkahle/randy_headshot_square.jpg"



# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.

#[[params.menu]]
#    before = true
#    label  = "Home"
#    link   = "/"

#[[params.menu]]
#    before = true
#    label = "Articles"
#    link = "/articles/"

#[[params.menu]]
#    before = true
#    label  = "Expertise"
#    link   = "/expertise/"

#[[params.menu]]
#    before = true
#    label  = "Contact"
#    link   = "/contact/"


#[[params.menu]]
#    before = false
#    label  = "Tags"
#    link   = "tags/"

#[[params.menu]]
#    before = false
#    label  = "Categories"
#    link   = "categories/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://github.com/resourcefulcomputing"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# create automatically.
    github          = "resourcefulcomputing"
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "datablissr"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true


   
